let elem = document.querySelector('p');


// -The user clicks an element
elem.addEventListener('click', function(){
    elem.style.fontSize = "26px";              //Each on of these events should trigger a change on the page that is visual.
})
//-The user hovers their mouse over an element
elem.addEventListener('mouseover', function(){
    elem.style.fontFamily = "tahoma";          //Each on of these events should trigger a change on the page that is visual.
})
//window is a high level element in javaScript and all variables and functions created in codes are children of that element
// -The user presses the space key on their keyboard
window.addEventListener('keyup',function(e){
     //.key is better practise because it returns the value of that property, as for .code or .keycode just returns the code of that physical button which makes using them better for things like games.
    if(e.key === " "){            
        elem.style.background = 'red';         //Each on of these events should trigger a change on the page that is visual.
    }else if(e.key === "Enter"){           
        elem.style.background = 'blue';        //Each on of these events should trigger a change on the page that is visual.
    // key gives you the value you generated by the button    
    }else if(e.key === "a"){
        elem.style.background = 'orange';      //Each on of these events should trigger a change on the page that is visual.
    //.code represents the physical button
    }else if(e.code === "KeyQ"){
        elem.style.background = 'black';
    }
    // console.log(e);
})




